// Code generated by MockGen. DO NOT EDIT.
// Source: app/repositories/sessions.go

// Package mock_repositories is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionsRepository is a mock of SessionsRepository interface.
type MockSessionsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsRepositoryMockRecorder
}

// MockSessionsRepositoryMockRecorder is the mock recorder for MockSessionsRepository.
type MockSessionsRepositoryMockRecorder struct {
	mock *MockSessionsRepository
}

// NewMockSessionsRepository creates a new mock instance.
func NewMockSessionsRepository(ctrl *gomock.Controller) *MockSessionsRepository {
	mock := &MockSessionsRepository{ctrl: ctrl}
	mock.recorder = &MockSessionsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionsRepository) EXPECT() *MockSessionsRepositoryMockRecorder {
	return m.recorder
}

// AddSession mocks base method.
func (m *MockSessionsRepository) AddSession(id int, additionalData string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSession", id, additionalData)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSession indicates an expected call of AddSession.
func (mr *MockSessionsRepositoryMockRecorder) AddSession(id, additionalData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSession", reflect.TypeOf((*MockSessionsRepository)(nil).AddSession), id, additionalData)
}

// GetIdBySession mocks base method.
func (m *MockSessionsRepository) GetIdBySession(secret string) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdBySession", secret)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIdBySession indicates an expected call of GetIdBySession.
func (mr *MockSessionsRepositoryMockRecorder) GetIdBySession(secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdBySession", reflect.TypeOf((*MockSessionsRepository)(nil).GetIdBySession), secret)
}

// RemoveSession mocks base method.
func (m *MockSessionsRepository) RemoveSession(secret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSession", secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSession indicates an expected call of RemoveSession.
func (mr *MockSessionsRepositoryMockRecorder) RemoveSession(secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSession", reflect.TypeOf((*MockSessionsRepository)(nil).RemoveSession), secret)
}
